baseURL = 'https://OrangeCocoa.github.io'
languageCode = 'ja-jp'
title = '天上天下唯我独尊備忘録雑記メモ覚書'
paginate = 10

# セクション名を自動で複数形化するのを防ぐ
pluralizeListTitles = false

# Markdown内でHTMLを直接書けるようになる
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Markdown内で任意のブロックにCSSを指定できるようになる
[markup.goldmark.parser.attribute]
  block = true

# サイトマップ設定
[sitemap]
  changefreq = "daily"
  priority = 0.5

# .Site.Menus.mainで取得できる
[menu]
  [[menu.main]]
    identifier = "index"
    name = "TOPページ"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/nav/archives/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/nav/about/"
    weight = 4
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/nav/search/"
    weight = 5